NCORES      = 4
XLEN        = 32
CPREFIX     = riscv-none-elf-
CFLAGS_ARCH = -march=rv32ima_zicsr_zifencei -mabi=ilp32 -mcmodel=medany -DDELAY_MS=1000
QEMU        = qemu-system-riscv32

include Makefile.common
