XLEN        = 32
RISCV_PREFIX = riscv32-unknown-elf

CC          = $(RISCV_PREFIX)-gcc
OBJDUMP     = $(RISCV_PREFIX)-objdump
OBJCOPY     = $(RISCV_PREFIX)-objcopy
NM          = $(RISCV_PREFIX)-nm

QEMU        = qemu-system-riscv32
CFLAGS_ARCH = -march=rv32ima_zicsr -mabi=ilp32

include Makefile.common
